/// <reference types="astro/client" />

// `Astro.locals.runtime.env` was removed in Astro v6 / @astrojs/cloudflare
// v14 — bindings are now read via `import { env } from 'cloudflare:workers'`
// instead. That module is a Workers-runtime built-in with no shipped type
// declarations in this toolchain, so it's declared here.
//
// `Env` itself comes from `worker-configuration.d.ts`, generated by
// `npm run cf-typegen` (gitignored — regenerate after editing the bindings
// in wrangler.jsonc).
declare module 'cloudflare:workers' {
  const env: Env;
  export { env };
}

// Cloudflare's Turnstile script (loaded via a plain <script src> tag, not
// an npm package) attaches this global. Minimal surface — just what
// coaching/index.astro's client script calls.
interface TurnstileGlobal {
  reset: (widgetId?: string) => void;
}

declare global {
  interface Window {
    turnstile?: TurnstileGlobal;
  }
}
